config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'password_resets/new'
  get    'password_resets/edit'

  get    'users/new'
  get    'sessions/new'
  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = I18n.t('msg_email_password_reset')
      redirect_to root_url
    else
      flash.now[:alert] = I18n.t('msg_email_not_found')
      render 'new'
    end
  end

  def edit
  end

  def update
    if password_blank?
      flash.now[:alert] = I18n.t('msg_password_not_blank')
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = I18n.t('msg_password_was_reset')
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Returns true if password is blank.
    def password_blank?
      params[:user][:password].blank?
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:alert] = I18n.t('msg_password_reset_expired')
        redirect_to new_password_reset_url
      end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, t('user_password_reset')) %>
<h2><%= yield(:title) %></h2>

<div class="row">
  <div class="large-12 columns large-centered">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, t('user_password') %>
      <%= f.password_field :password, autofocus: true %>

      <%= f.label :password_confirmation, t('user_password_confirm') %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit t('btn_user_password_update'), class: "button radius primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, t('user_password_reset')) %>
<h2><%= yield(:title) %></h2>

<div class="row">
  <div class="large-12 columns large-centered">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true %>

      <%= f.submit t('btn_submit'), class: "button radius primary" %>
    <% end %>
  </div>
</div>