config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'password_resets/new'
  get    'password_resets/edit'

  get    'users/new'
  get    'sessions/new'
  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p><small><%= t('copyright') %></small></p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><%= link_to t('about'),   about_path %></li>
          <li><%= link_to t('contact'), contact_path %></li>
          <li><a href="#"><%= t('news') %></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%# navigation header styled for Zurb Foundation 5 %>

<header class="header">

  <!-- Off Canvas Menu -->
  <aside class="right-off-canvas-menu">
    <!-- whatever you want goes here -->
    <ul class="off-canvas-list">
      <li><label><%= t('appname') %></label></li>
      <li><%= link_to t('home'), root_path, class: "navtop_link" %></li>
      <% if logged_in? %>
         <li><%= link_to t('users'), users_path %></li>
      <% end %>
      <li><%= link_to t('about'), about_path, class: "navtop_link" %></li>
      <li><%= link_to t('help'),  help_path, class: "navtop_link" %></li>
      <% if logged_in? %>
        <li><%= link_to t('logout'), logout_path, class: "navtop_link", method: "delete" %></li>
        <li><%= link_to current_user.email, edit_user_path(current_user) %></li>
      <% else %>
        <li><%= link_to t('login'), login_path, class: "navtop_link" %></li>
      <% end %>
      <li>"  "</li>
    </ul>
  </aside>

  <div class="row fullWidth">
    <nav class="top-bar" role="navigation" data-options="sticky_on: large">
  	  <ul class="title-area">
  	    <li class="name">
  	      <h1><a href="#" class="navtop_link"><%= image_tag("mblog.png", :alt => "rss feed") %> <%= t('appname') %></a></h1>
  	    </li>
        <li class="toggle-topbar menu-icon"><a class="right-off-canvas-toggle" href="#"><span><%= t('menu') %></span></a></li>
  	  </ul>

  	  <section class="top-bar-section">
  	    <!-- Right Nav Section -->
  	    <ul class="right">
  	    	<li><%= link_to t('about'), about_path, class: "navtop_link" %></li>
  	    	<li><%= link_to t('help'),  help_path, class: "navtop_link" %></li>
  	    	<% if logged_in? %>
  				  <li><%= link_to t('logout'), logout_path, class: "navtop_link", method: "delete" %></li>
  				  <li><%= link_to current_user.email, edit_user_path(current_user) %></li>
  				<% else %>
  				  <li><%= link_to t('login'), login_path, class: "navtop_link" %></li>
  				<% end %>
  	      <li>"  "</li>

  	    </ul>

  	    <!-- Left Nav Section -->
  	    <ul class="left">
  	      <li><%= link_to t('home'), root_path, class: "navtop_link" %></li>
          <% if logged_in? %>
      		   <li><%= link_to "Users", users_path %></li>
          <% end %>
  	    </ul>
  	  </section>

  	</nav>
  </div>

  <!-- close the off-canvas menu -->
  <a class="exit-off-canvas"></a>

</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s %>">
      <big><strong>
	      <%= content_tag :div, msg %>
	      <a href="#" class="close">&times;</a>
      </strong></big>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Userfw" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">

        <%= render 'layouts/header' %>

        <main role="main">
        	<div class="row">
      			<div class="small-12 small-centered columns">
    	      	<%= render 'layouts/messages' %>
    	      	<%= yield %>
    	      	<%= render 'layouts/footer' %>
              <!--
              <div class="panel callout radius">
                <%= debug(params) if Rails.env.development? %>
              </div>
            -->
           </div>
          </div>
        </main>

      </div>
    </div>

  </body>
</html>